import type { RoadbookState, SkillNode, ResearchResult } from "../types.js";

interface Labels {
  highPriority: string;
  medPriority: string;
  lowPriority: string;
  category: string;
  subSkills: string;
  relatedConcepts: string;
  resources: string;
  skillMap: string;
  learningPath: string;
  nodeCount: (n: number) => string;
  generatedBy: string;
}

const LABELS: Record<string, Labels> = {
  "Chinese (Simplified)": {
    highPriority: "高优先级", medPriority: "中优先级", lowPriority: "低优先级",
    category: "分类", subSkills: "子技能", relatedConcepts: "相关概念",
    resources: "推荐资源", skillMap: "技能图谱", learningPath: "学习路径",
    nodeCount: (n) => `共 ${n} 个技能节点，按优先级排列：`,
    generatedBy: "由 Ariadne 引擎自动生成",
  },
  "Japanese": {
    highPriority: "高優先度", medPriority: "中優先度", lowPriority: "低優先度",
    category: "カテゴリ", subSkills: "サブスキル", relatedConcepts: "関連概念",
    resources: "推奨リソース", skillMap: "スキルマップ", learningPath: "学習パス",
    nodeCount: (n) => `${n} 個のスキルノード（優先度順）：`,
    generatedBy: "Ariadne エンジンによる自動生成",
  },
  "Spanish": {
    highPriority: "Alta prioridad", medPriority: "Media prioridad", lowPriority: "Baja prioridad",
    category: "Categoría", subSkills: "Sub-habilidades", relatedConcepts: "Conceptos relacionados",
    resources: "Recursos recomendados", skillMap: "Mapa de habilidades", learningPath: "Ruta de aprendizaje",
    nodeCount: (n) => `${n} nodos de habilidad, ordenados por prioridad:`,
    generatedBy: "Generado automáticamente por el motor Ariadne",
  },
  "French": {
    highPriority: "Haute priorité", medPriority: "Priorité moyenne", lowPriority: "Basse priorité",
    category: "Catégorie", subSkills: "Sous-compétences", relatedConcepts: "Concepts associés",
    resources: "Ressources recommandées", skillMap: "Carte des compétences", learningPath: "Parcours d'apprentissage",
    nodeCount: (n) => `${n} nœuds de compétences, classés par priorité :`,
    generatedBy: "Généré automatiquement par le moteur Ariadne",
  },
};

const DEFAULT_LABELS: Labels = {
  highPriority: "High Priority", medPriority: "Medium Priority", lowPriority: "Low Priority",
  category: "Category", subSkills: "Sub-skills", relatedConcepts: "Related Concepts",
  resources: "Recommended Resources", skillMap: "Skill Map", learningPath: "Learning Path",
  nodeCount: (n) => `${n} skill nodes, sorted by priority:`,
  generatedBy: "Auto-generated by Ariadne engine",
};

function getLabels(language: string): Labels {
  return LABELS[language] ?? DEFAULT_LABELS;
}

function buildMermaidMindmap(title: string, skills: SkillNode[]): string {
  const lines: string[] = ["```mermaid", "mindmap", `  root((${title}))`];

  const grouped = new Map<string, SkillNode[]>();
  for (const skill of skills) {
    const list = grouped.get(skill.category) ?? [];
    list.push(skill);
    grouped.set(skill.category, list);
  }

  for (const [category, nodes] of grouped) {
    lines.push(`    ${category}`);
    for (const node of nodes) {
      const badge = node.priority === "high" ? "🔴" : node.priority === "medium" ? "🟡" : "🟢";
      lines.push(`      ${badge} ${node.name}`);
      for (const sub of node.subSkills.slice(0, 3)) {
        lines.push(`        ${sub}`);
      }
    }
  }

  lines.push("```");
  return lines.join("\n");
}

function buildSkillSection(
  skill: SkillNode,
  index: number,
  research: ResearchResult | undefined,
  labels: Labels,
): string {
  const badge = skill.priority === "high" ? `🔴 ${labels.highPriority}`
    : skill.priority === "medium" ? `🟡 ${labels.medPriority}`
    : `🟢 ${labels.lowPriority}`;

  const lines = [
    `### ${index + 1}. ${skill.name}`,
    "",
    `> ${badge} | ${labels.category}: ${skill.category}`,
    "",
    skill.description,
    "",
    `**${labels.subSkills}:**`,
    ...skill.subSkills.map((s) => `- ${s}`),
    "",
    `**${labels.relatedConcepts}:**`,
    ...skill.relatedConcepts.map((c) => `- ${c}`),
    "",
  ];

  if (research && research.resources.length > 0) {
    lines.push(`**${labels.resources}:**`);
    for (const r of research.resources) {
      lines.push(`- [${r.title}](${r.url})`);
      if (r.snippet) lines.push(`  > ${r.snippet}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function generateRoadbookMarkdown(
  state: Pick<RoadbookState, "title" | "skillTree" | "researchResults" | "language">,
): Partial<RoadbookState> {
  const { title, skillTree, researchResults, language } = state;
  const labels = getLabels(language ?? "English");

  const sorted = [...skillTree].sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return order[a.priority] - order[b.priority];
  });

  const researchMap = new Map<string, ResearchResult>(
    researchResults.map((r) => [r.skillName, r]),
  );

  const sections = [
    `# ${title}`,
    "",
    `> ${labels.generatedBy} | ${new Date().toLocaleDateString("en-CA")}`,
    "",
    "---",
    "",
    `## ${labels.skillMap}`,
    "",
    buildMermaidMindmap(title, sorted),
    "",
    "---",
    "",
    `## ${labels.learningPath}`,
    "",
    labels.nodeCount(sorted.length),
    "",
    ...sorted.map((s, i) => buildSkillSection(s, i, researchMap.get(s.name), labels)),
    "---",
    "",
    "*Generated by [Roadbook](https://github.com/jackjin1997/Roadbook)*",
  ];

  return { roadbookMarkdown: sections.join("\n") };
}
